version: '3'
services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - networkName

  voting-app:
    image: voting-app
    ports:
      - 5001:80
    links:
      - redis

  worker-app:
    image: worker
    links:
      - redis
      - db

  result-app:
    image: result-app
    ports:
      - 5002:80
    links:
      - db